export const GENRES = [
  'All',
  'Lifestyle',
  'Business',
  'Entertainment',
  'Science',
  'Art',
  'Sports',
  'Technology',
  'Health',
  'Travel',
  'Food',
  'Education',
  'Love & Relationships',
  'Poetry',
  'Cinema',
  'Film Reviews',
  'Music',
  'Theatre',
  'Photography',
  'Dance',
  'Comics & Graphic Novels',
  'Fiction',
  'Non-Fiction',
  'Short Stories',
  'Book Reviews',
  'Writing Tips',
  'Creative Writing',
  'Culture & Traditions',
  'History',
  'Philosophy',
  'Politics',
  'Feminism',
  'Spirituality',
  'Mindfulness',
  'Minimalism',
  'Motivational',
  'Productivity',
  'Life Lessons',
  'Freelancing',
  'Career Advice',
  'Job Search',
  'Workplace Culture',
  'Remote Work',
  'Startup Life',
  'AI & Machine Learning',
  'Coding & Development',
  'Gadgets & Reviews',
  'Cybersecurity',
  'Blockchain & Crypto',
  'Adventure',
  'Backpacking',
  'Digital Nomad Life',
  'Local Guides',
  'Cultural Exchange',
  'Parenting',
  'Mental Health',
  'Self-Improvement',
  'Personal Journals'
];

export const READING_LEVELS = ['beginner', 'intermediate', 'advanced'];
