const blogCategory = Object.freeze({
    ALL: 'All',
    ADVENTURE: 'Adventure',
    AI_AND_MACHINE_LEARNING: 'AI & Machine Learning',
    ART: 'Art',
    BACKPACKING: 'Backpacking',
    BLOCKCHAIN_AND_CRYPTO: 'Blockchain & Crypto',
    BOOK_REVIEWS: 'Book Reviews',
    BUSINESS: 'Business',
    CAREER_ADVICE: 'Career Advice',
    CINEMA: 'Cinema',
    CODING_AND_DEVELOPMENT: 'Coding & Development',
    COMICS_AND_GRAPHIC_NOVELS: 'Comics & Graphic Novels',
    CREATIVE_WRITING: 'Creative Writing',
    CULTURAL_EXCHANGE: 'Cultural Exchange',
    CULTURE_AND_TRADITIONS: 'Culture & Traditions',
    CYBERSECURITY: 'Cybersecurity',
    DANCE: 'Dance',
    DIGITAL_NOMAD_LIFE: 'Digital Nomad Life',
    EDUCATION: 'Education',
    ENTERTAINMENT: 'Entertainment',
    FEMINISM: 'Feminism',
    FICTION: 'Fiction',
    FILM_REVIEWS: 'Film Reviews',
    FOOD: 'Food',
    FREELANCING: 'Freelancing',
    GADGETS_AND_REVIEWS: 'Gadgets & Reviews',
    HEALTH: 'Health',
    HISTORY: 'History',
    JOB_SEARCH: 'Job Search',
    LIFE_LESSONS: 'Life Lessons',
    LIFESTYLE: 'Lifestyle',
    LOCAL_GUIDES: 'Local Guides',
    LOVE_AND_RELATIONSHIPS: 'Love & Relationships',
    MENTAL_HEALTH: 'Mental Health',
    MINDFULNESS: 'Mindfulness',
    MOTIVATIONAL: 'Motivational',
    MUSIC: 'Music',
    NON_FICTION: 'Non-Fiction',
    PARENTING: 'Parenting',
    PERSONAL_JOURNALS: 'Personal Journals',
    PHILOSOPHY: 'Philosophy',
    PHOTOGRAPHY: 'Photography',
    POETRY: 'Poetry',
    POLITICS: 'Politics',
    PRODUCTIVITY: 'Productivity',
    REMOTE_WORK: 'Remote Work',
    SCIENCE: 'Science',
    SELF_IMPROVEMENT: 'Self-Improvement',
    SHORT_STORIES: 'Short Stories',
    SPIRITUALITY: 'Spirituality',
    SPORTS: 'Sports',
    STARTUP_LIFE: 'Startup Life',
    TECHNOLOGY: 'Technology',
    THEATRE: 'Theatre',
    TRAVEL: 'Travel',
    WRITING_TIPS: 'Writing Tips',
});

export default blogCategory;