const getGenreColor = (genre) => {
  const colors = {
    'Adventure': 'bg-green-700',
    'AI & Machine Learning': 'bg-fuchsia-600',
    'All': 'bg-gray-500',
    'Art': 'bg-orange-500',
    'Backpacking': 'bg-amber-600',
    'Blockchain & Crypto': 'bg-yellow-700',
    'Book Reviews': 'bg-lime-500',
    'Business': 'bg-blue-500',
    'Career Advice': 'bg-indigo-300',
    'Cinema': 'bg-violet-500',
    'Coding & Development': 'bg-purple-600',
    'Comics & Graphic Novels': 'bg-yellow-600',
    'Creative Writing': 'bg-teal-400',
    'Culture & Traditions': 'bg-orange-400',
    'Cultural Exchange': 'bg-emerald-700',
    'Cybersecurity': 'bg-red-700',
    'Dance': 'bg-red-400',
    'Digital Nomad Life': 'bg-indigo-700',
    'Education': 'bg-teal-500',
    'Entertainment': 'bg-purple-500',
    'Feminism': 'bg-pink-600',
    'Fiction': 'bg-sky-600',
    'Film Reviews': 'bg-purple-400',
    'Food': 'bg-yellow-500',
    'Freelancing': 'bg-blue-300',
    'Gadgets & Reviews': 'bg-orange-600',
    'Health': 'bg-emerald-500',
    'History': 'bg-stone-500',
    'Job Search': 'bg-amber-400',
    'Life Lessons': 'bg-emerald-600',
    'Lifestyle': 'bg-pink-500',
    'Local Guides': 'bg-blue-700',
    'Love & Relationships': 'bg-rose-500',
    'Mental Health': 'bg-rose-400',
    'Mindfulness': 'bg-green-600',
    'Minimalism': 'bg-slate-500',
    'Motivational': 'bg-lime-600',
    'Music': 'bg-pink-400',
    'Non-Fiction': 'bg-blue-600',
    'Parenting': 'bg-pink-300',
    'Personal Journals': 'bg-gray-600',
    'Philosophy': 'bg-neutral-600',
    'Photography': 'bg-amber-500',
    'Poetry': 'bg-fuchsia-500',
    'Politics': 'bg-red-600',
    'Productivity': 'bg-cyan-600',
    'Remote Work': 'bg-cyan-300',
    'Science': 'bg-green-500',
    'Self-Improvement': 'bg-lime-400',
    'Short Stories': 'bg-blue-400',
    'Spirituality': 'bg-indigo-600',
    'Sports': 'bg-red-500',
    'Startup Life': 'bg-teal-300',
    'Technology': 'bg-cyan-500',
    'Theatre': 'bg-indigo-400',
    'Travel': 'bg-indigo-500',
    'Writing Tips': 'bg-green-400',
    'Workplace Culture': 'bg-zinc-500'
  };

  return colors[genre] || 'bg-gray-600';
};

export default getGenreColor;
