export const genres = [
    { value: 'All', label: 'All Categories', icon: '🌐', color: 'bg-gray-600' },
    { value: 'Adventure', label: 'Adventure', icon: '⛰️', color: 'bg-green-700' },
    { value: 'AI & Machine Learning', label: 'AI & Machine Learning', icon: '🤖', color: 'bg-fuchsia-600' },
    { value: 'Art', label: 'Art', icon: '🎨', color: 'bg-indigo-600' },
    { value: 'Backpacking', label: 'Backpacking', icon: '🎒', color: 'bg-amber-600' },
    { value: 'Blockchain & Crypto', label: 'Blockchain & Crypto', icon: '🪙', color: 'bg-yellow-700' },
    { value: 'Book Reviews', label: 'Book Reviews', icon: '📚', color: 'bg-lime-500' },
    { value: 'Business', label: 'Business', icon: '💼', color: 'bg-blue-600' },
    { value: 'Career Advice', label: 'Career Advice', icon: '📋', color: 'bg-indigo-300' },
    { value: 'Cinema', label: 'Cinema', icon: '🎞️', color: 'bg-violet-500' },
    { value: 'Coding & Development', label: 'Coding & Development', icon: '👨‍💻', color: 'bg-purple-600' },
    { value: 'Comics & Graphic Novels', label: 'Comics & Graphic Novels', icon: '📖', color: 'bg-yellow-600' },
    { value: 'Creative Writing', label: 'Creative Writing', icon: '🖋️', color: 'bg-teal-400' },
    { value: 'Culture & Traditions', label: 'Culture & Traditions', icon: '🕌', color: 'bg-orange-400' },
    { value: 'Cultural Exchange', label: 'Cultural Exchange', icon: '🌏', color: 'bg-emerald-700' },
    { value: 'Cybersecurity', label: 'Cybersecurity', icon: '🔒', color: 'bg-red-700' },
    { value: 'Dance', label: 'Dance', icon: '💃', color: 'bg-red-400' },
    { value: 'Digital Nomad Life', label: 'Digital Nomad Life', icon: '🌍', color: 'bg-indigo-700' },
    { value: 'Education', label: 'Education', icon: '📚', color: 'bg-emerald-600' },
    { value: 'Entertainment', label: 'Entertainment', icon: '🎬', color: 'bg-purple-600' },
    { value: 'Feminism', label: 'Feminism', icon: '♀️', color: 'bg-pink-600' },
    { value: 'Fiction', label: 'Fiction', icon: '📘', color: 'bg-sky-600' },
    { value: 'Film Reviews', label: 'Film Reviews', icon: '📽️', color: 'bg-purple-400' },
    { value: 'Food', label: 'Food', icon: '🍳', color: 'bg-yellow-600' },
    { value: 'Freelancing', label: 'Freelancing', icon: '🧑‍💻', color: 'bg-blue-300' },
    { value: 'Gadgets & Reviews', label: 'Gadgets & Reviews', icon: '📱', color: 'bg-orange-600' },
    { value: 'Health', label: 'Health', icon: '🏥', color: 'bg-red-600' },
    { value: 'History', label: 'History', icon: '🏛️', color: 'bg-stone-500' },
    { value: 'Job Search', label: 'Job Search', icon: '🔍', color: 'bg-amber-400' },
    { value: 'Lifestyle', label: 'Lifestyle', icon: '🌟', color: 'bg-pink-600' },
    { value: 'Life Lessons', label: 'Life Lessons', icon: '🧩', color: 'bg-emerald-600' },
    { value: 'Local Guides', label: 'Local Guides', icon: '🗺️', color: 'bg-blue-700' },
    { value: 'Love & Relationships', label: 'Love & Relationships', icon: '❤️', color: 'bg-rose-500' },
    { value: 'Mental Health', label: 'Mental Health', icon: '🧠', color: 'bg-rose-400' },
    { value: 'Mindfulness', label: 'Mindfulness', icon: '🧠', color: 'bg-green-600' },
    { value: 'Minimalism', label: 'Minimalism', icon: '🧺', color: 'bg-slate-500' },
    { value: 'Motivational', label: 'Motivational', icon: '🔥', color: 'bg-lime-600' },
    { value: 'Music', label: 'Music', icon: '🎵', color: 'bg-pink-400' },
    { value: 'Non-Fiction', label: 'Non-Fiction', icon: '📗', color: 'bg-blue-600' },
    { value: 'Parenting', label: 'Parenting', icon: '🧒', color: 'bg-pink-300' },
    { value: 'Personal Journals', label: 'Personal Journals', icon: '📔', color: 'bg-gray-600' },
    { value: 'Philosophy', label: 'Philosophy', icon: '🤔', color: 'bg-neutral-600' },
    { value: 'Photography', label: 'Photography', icon: '📸', color: 'bg-amber-500' },
    { value: 'Poetry', label: 'Poetry', icon: '📝', color: 'bg-fuchsia-500' },
    { value: 'Politics', label: 'Politics', icon: '🏛️', color: 'bg-red-600' },
    { value: 'Productivity', label: 'Productivity', icon: '📈', color: 'bg-cyan-600' },
    { value: 'Remote Work', label: 'Remote Work', icon: '🏠', color: 'bg-cyan-300' },
    { value: 'Science', label: 'Science', icon: '🔬', color: 'bg-green-600' },
    { value: 'Self-Improvement', label: 'Self-Improvement', icon: '🚴', color: 'bg-lime-400' },
    { value: 'Short Stories', label: 'Short Stories', icon: '📕', color: 'bg-blue-400' },
    { value: 'Spirituality', label: 'Spirituality', icon: '🧘', color: 'bg-indigo-600' },
    { value: 'Sports', label: 'Sports', icon: '⚽', color: 'bg-orange-600' },
    { value: 'Startup Life', label: 'Startup Life', icon: '🚀', color: 'bg-teal-300' },
    { value: 'Technology', label: 'Technology', icon: '💻', color: 'bg-cyan-600' },
    { value: 'Theatre', label: 'Theatre', icon: '🎭', color: 'bg-indigo-400' },
    { value: 'Travel', label: 'Travel', icon: '✈️', color: 'bg-teal-600' },
    { value: 'Writing Tips', label: 'Writing Tips', icon: '✍️', color: 'bg-green-400' },
    { value: 'Workplace Culture', label: 'Workplace Culture', icon: '🏢', color: 'bg-zinc-500' }
];